### ISSUE TITLE
Can it export to Markdown ?

### ISSUE THREAD

**Issue by berserkwarwolf** [jorisschellekens/ptext-release#1]
I was wondering how is the extracted content exported. Can it export to Markdown ?

**Comment by jorisschellekens** [comment]
Hi there,

Yes, pText can export to markdown.
This functionality was present in an earlier release, and is currently being refactored.

The basic idea is to process all text rendering instructions in a pdf, and build a map of where each letter of the document is rendered.

Then neighbouring letters are merged into words and lines of text (depending how far apart they are, and whether the gap is wider than the width of the space character in that font).

Lines are subsequently merged into paragraphs, depending on the leading (that is the distance between the baselines) and their horizontal overlap.

SimpleParagraphExtraction already goes as far as this step of the process.

The next step is to use that information to build a markdown document.

In order to figure out which paragraph is a title or subtitle, you could look at font information (size, color, bold).

I expect the basic markdown export to be up and running again soon.
